sudo: required
services:
  - docker

before_install:
  - docker build -t ddutjnrevenge-universe/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true ddutjnrevenge-universe/docker-react npm run test